# Generated by Django 5.2.1 on 2025-06-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_remove_project_images_projectimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="live_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
