# Generated by Django 5.2.1 on 2025-06-21 15:40

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_project_live_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
    ]
