# Generated by Django 5.2.1 on 2025-06-23 07:08

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_project_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="auto_slug",
            field=autoslug.fields.AutoSlugField(
                blank=True,
                editable=False,
                null=True,
                populate_from="title",
                unique=True,
            ),
        ),
    ]
