# Generated by Django 5.2.1 on 2025-06-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_project_header"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project_header",
            name="header_des",
            field=models.TextField(),
        ),
    ]
