# Generated by Django 5.2.1 on 2025-06-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("educ_title", models.CharField(verbose_name=50)),
                ("educ_des", models.CharField(verbose_name=50)),
                ("educ_camp", models.CharField(verbose_name=30)),
                ("educ_camp1", models.CharField(verbose_name=30)),
                ("educ_start_date", models.CharField(verbose_name=40)),
                ("educ_end_date", models.CharField(verbose_name=40)),
                ("educ_durations", models.CharField(verbose_name=30)),
                ("educ_certifi", models.CharField(verbose_name=30)),
                ("educ_camp_id", models.CharField(verbose_name=30)),
                ("educ_verify", models.URLField()),
            ],
        ),
    ]
