# Generated by Django 5.2.1 on 2025-06-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="educ_camp",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="education",
            name="educ_camp1",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="education",
            name="educ_camp_id",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="education",
            name="educ_certifi",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="education",
            name="educ_des",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="education",
            name="educ_durations",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="education",
            name="educ_end_date",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="education",
            name="educ_start_date",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="education",
            name="educ_title",
            field=models.CharField(max_length=50),
        ),
    ]
