# Generated by Django 5.2.1 on 2025-06-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "education",
            "0002_alter_education_educ_camp_alter_education_educ_camp1_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="educ_camp",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="educ_camp1",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="educ_camp_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="educ_certifi",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="educ_des",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="educ_durations",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="educ_end_date",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="educ_start_date",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="educ_title",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="educ_verify",
            field=models.URLField(blank=True, null=True),
        ),
    ]
