# Generated by Django 5.2.1 on 2025-06-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Tags", "0002_alter_blog_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
