# Generated by Django 5.2.1 on 2025-06-19 10:14

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Tags", "0003_alter_blog_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="slugs",
            field=autoslug.fields.AutoSlugField(
                blank=True,
                editable=False,
                null=True,
                populate_from="title",
                unique=True,
            ),
        ),
    ]
