# Generated by Django 5.2.1 on 2025-06-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Tags", "0004_blog_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="images",
            field=models.ImageField(default=None, upload_to="blogs"),
        ),
    ]
