# Generated by Django 5.2.1 on 2025-06-19 12:47

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Tags", "0007_blog_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
