# Generated by Django 5.2.1 on 2025-06-23 13:37

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Tags", "0008_alter_blog_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog_Header",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blog_title", models.CharField(max_length=50)),
                ("blog_des", tinymce.models.HTMLField()),
            ],
        ),
    ]
