# Generated by Django 5.2.1 on 2025-06-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Tags", "0009_blog_header"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog_header",
            name="blog_des",
            field=models.TextField(),
        ),
    ]
