# Generated by Django 5.2.1 on 2025-06-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("header", "0002_cv_logs"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logs", models.FileField(blank=True, null=True, upload_to="logo")),
            ],
        ),
        migrations.RemoveField(
            model_name="cv",
            name="logs",
        ),
    ]
