# Generated by Django 5.2.1 on 2025-06-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="socail_media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("social_image", models.ImageField(upload_to="socilamedia")),
                ("socila_link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="social_header",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("socila_header", models.CharField(max_length=20)),
            ],
        ),
    ]
