# Generated by Django 5.2.1 on 2025-06-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="social_header",
            name="socila_header",
            field=models.CharField(max_length=50),
        ),
    ]
