# Generated by Django 5.2.1 on 2025-06-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.ImageField(upload_to="logo")),
                ("footer_about", models.TextField()),
                ("footer_location", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("linkedin_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("copyright", models.CharField(max_length=255)),
            ],
        ),
    ]
