# Generated by Django 5.2.1 on 2025-06-19 03:58

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="home_slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slide_first_des", models.CharField(max_length=30)),
                ("slide_name", models.CharField(max_length=30)),
                ("slide_des", tinymce.models.HTMLField()),
                ("slide_image", models.ImageField(upload_to="mainslider")),
                ("slide_icone_one", models.ImageField(upload_to="mainslider")),
                ("slide_icone_two", models.ImageField(upload_to="mainslider")),
            ],
        ),
    ]
