# Generated by Django 5.2.1 on 2025-06-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home_slider", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="home_slider",
            name="slide_name",
        ),
        migrations.AddField(
            model_name="home_slider",
            name="slide_name_part_one",
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name="home_slider",
            name="slide_name_part_two",
            field=models.CharField(default=None, max_length=30),
        ),
    ]
