# Generated by Django 5.2.1 on 2025-06-19 04:19

import home_slider.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home_slider", "0002_remove_home_slider_slide_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home_slider",
            name="slide_icone_one",
            field=models.FileField(
                upload_to="mainslider", validators=[home_slider.models.validate_svg]
            ),
        ),
        migrations.AlterField(
            model_name="home_slider",
            name="slide_icone_two",
            field=models.FileField(
                upload_to="mainslider", validators=[home_slider.models.validate_svg]
            ),
        ),
    ]
