# Generated by Django 5.2.1 on 2025-06-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home_slider", "0003_alter_home_slider_slide_icone_one_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_text", models.CharField(max_length=20)),
                ("skill_image", models.ImageField(upload_to="skills")),
            ],
        ),
    ]
