# Generated by Django 5.2.1 on 2025-06-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home_slider", "0005_skills_author_skills_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skills",
            name="skill_text",
            field=models.CharField(max_length=50),
        ),
    ]
