# Generated by Django 5.2.1 on 2025-06-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home_slider", "0006_alter_skills_skill_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="skills",
            name="category",
            field=models.CharField(
                choices=[
                    ("Programming", "Programming Languages"),
                    ("Framework", "Frameworks & Libraries"),
                    ("Visualization", "Data Visualization & BI"),
                    ("Web", "Web & CMS"),
                    ("DevOps", "DevOps & Hosting"),
                ],
                default="Programming",
                max_length=50,
            ),
        ),
    ]
