# Generated by Django 5.2.1 on 2025-06-22 05:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home_slider", "0007_skills_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skills",
            name="category",
        ),
    ]
